name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: ./build.sh
      - name: archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: losungen.epub
          path: build/books/losungen*.epub

